<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>${book.name!"-- не указано --"}</title>
</head>
<body>
    <h1>${book.name!"-- не указано --"}</h1>
    <div>
        <h2>Описание</h2>
        <p>${book.description!"-- не указано --"}</p>
        <img src="${book.photo}" alt="Book Image">
    </div>
</body>
</html>
